# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#


#version: 2.1

executors:
  shopizer-ci:
    docker:
      - image: shopizerecomm/ci:latest
        auth:
          username: shopizerecomm
          password: $DOCKERHUB_PASSWORD  


#working_directory: ~/shopizer

version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    #docker:
    #  - image: shopizerecomm/ci:latest
    #    auth:
    #      username: shopizerecomm
    #      password: $DOCKERHUB_PASSWORD  
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "shopizer build and test (3)"
      - run:
          name: Run shell script
          command: |
            set -x
            /home/shopizer/tools/shopizer.sh tests
  #test:
  #  docker:
  #    - image: shopizerecomm/ci:latest
  #      auth:
  #        username: shopizerecomm
  #        password: $DOCKERHUB_PASSWORD  
  #  steps:
  #    - checkout
  #    - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      #- test:
      #    requires:
      #      - build


#jobs:
#  build:
#    steps:
#      - checkout
#      - run: echo "this is the build job"
#  test:
    #executor: shopizer-ci
#    steps:
#      - checkout
#      - run: echo "this is the test job"
      #- run: shopizer tests



#workflows:
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build